### ISSUE TITLE
Remove all but the org.eclipse.emf.ecoretools.design feature

### ISSUE THREAD

**Issue by pcdavid** [eclipse-ecoretools/ecoretools#4]
The Ecore Tools repo contains several plug-ins and features beside the main `org.eclipse.emf.ecoretools.design` (the only one contributed to the SimRel and [included in the Modeling Package](https://github.com/eclipse-packaging/packages/blob/master/packages/org.eclipse.epp.package.modeling.product/epp.product#LL246C6-L246C75)) which are not really maintained. Given the very limited time available to maintain the project, I propose we simply remove them to make things clearer and simpler to maintain.

Would be kept:
* org.eclipse.emf.ecoretools.build (releng)
* org.eclipse.emf.ecoretools.design-feature (the main feature)
* all the plug-ins actually part of that feature:
  * org.eclipse.emf.ecoretools
  * org.eclipse.emf.ecoretools.ui
  * org.eclipse.emf.ecoretools.design
  * org.eclipse.emf.ecoretools.design.ui
  * org.eclipse.emf.ecoretools.doc
* org.eclipse.emf.ecoretools.update (p2 repo)
* org.eclipse.emf.ecoretools.design.tests (tests, not packaged)

@cbrun WDYT?

**Comment by cbrun** [comment]
I'd like that, that would make things clearer indeed.

**Comment by pcdavid** [comment]
Done: https://github.com/eclipse-ecoretools/ecoretools/commit/a7dda67ca5a0575c83ec23c0e0c4064c901d97ca
